version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ai-agent-app
    contain_container_name: ai-agent-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - ai-agent-network

  db:
    image: mysql:8.0
    contain_container_name: ai-agent-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - ai-agent-network

  redis:
    image: redis:alpine
    contain_container_name: ai-agent-redis
    restart: unless-stopped
    networks:
      - ai-agent-network

  nginx:
    image: nginx:alpine
    contain_container_name: ai-agent-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - ai-agent-network

networks:
  ai-agent-network:
    driver: bridge
